name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adoptopenjdk'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: projeto-icecandylovers
          path: target/icecandylovers-0.0.1-SNAPSHOT.jar

      - name: Deploy to EC2
        run: |
          scp -i ~/.ssh/my-key.pem target/icecandylovers-0.0.1-SNAPSHOT.jar ubuntu@3.227.20.86:/home/ubuntu/
          ssh -i ~/.ssh/my-key.pem ubuntu@3.227.20.86 << 'EOF'
          sudo systemctl stop projeto-icecandylovers.service || true
          sudo mv /home/ubuntu/icecandylovers-0.0.1-SNAPSHOT.jar /opt/projeto-icecandylovers/icecandylovers.jar
          sudo systemctl start projeto-icecandylovers.service
          EOF
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}