name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
          cache-dependency-path: 'icecandylovers/pom.xml' # optional

      - name: Build with Maven
        run: mvn clean install --file pom.xml

      - name: Deploy to EC2
        run: |
          mkdir -p ~/.ssh
          echo "$PRIVATE_KEY" > ~/.ssh/my-key.pem
          chmod 600 ~/.ssh/my-key.pem
          
          # Add EC2 instance to known_hosts to avoid "Host key verification failed"
          ssh-keyscan -H 3.227.20.86 >> ~/.ssh/known_hosts
          
          # SCP and SSH commands
          scp -i ~/.ssh/my-key.pem target/icecandylovers-0.0.1-SNAPSHOT.jar ubuntu@3.227.20.86:/home/ubuntu/
          ssh -i ~/.ssh/my-key.pem ubuntu@3.227.20.86 << 'EOF'
          sudo systemctl stop projeto-icecandylovers.service || true
          sudo mv /home/ubuntu/icecandylovers-0.0.1-SNAPSHOT.jar /opt/projeto-icecandylovers/icecandylovers.jar
          sudo systemctl start projeto-icecandylovers.service
          EOF
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
