name: "DEV DEPLOY"

on:
  push:
    branches:
      - dev

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml
    with:
      environment: dev
      aws-assume-role-arn: "arn:aws:iam::767397900153:role/github-actions-gilrossi-pipeline"
      aws-region: "us-east-1"
      aws-statefile-s3-bucket: "icecandylovers-us-east-1-terraform-statefile"
      aws-lock-dynamodb-table: "icecandylovers-us-east-1-terraform-lock"