stages:
  - terraform

terraform:
  stage: terraform
  image: hashicorp/terraform:latest
  before_script:
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan github.com >> ~/.ssh/known_hosts
  script:
    - terraform init
    - terraform apply -auto-approve